keyword_list = [
    "software",
    "project",
    "development",
    "code",
    "programming",
    "source code",
    "version control",
    "repository",
    "commit",
    "branch",
    "merge",
    "bug",
    "issue",
    "debugging",
    "testing",
    "test case",
    "test suite",
    "automation",
    "continuous integration",
    "deployment",
    "release",
    "documentation",
    "API",
    "framework",
    "library",
    "dependency",
    "architecture",
    "design",
    "algorithm",
    "data structure",
    "database",
    "query",
    "backend",
    "frontend",
    "UI",
    "UX",
    "user interface",
    "user experience",
    "server",
    "client",
    "cloud",
    "container",
    "microservices",
    "RESTful",
    "API endpoint",
    "web service",
    "security",
    "authentication",
    "authorization",
    "encryption",
    "performance",
    "scalability",
    "agile",
    "sprint",
    "user story",
    "product backlog",
    "sprint backlog",
    "scrum master",
    "kanban",
    "CI/CD",
    "DevOps",
    "monitoring",
    "logging",
    "analytics",
    "machine learning",
    "artificial intelligence",
    "data science",
    "data analysis",
    "feature",
    "enhancement",
    "requirement",
    "specification",
    "documentation",
    "workflow",
    "task",
    "issue tracker",
    "Jira",
    "Git",
    "GitHub",
    "Bitbucket",
    "GitLab",
    "Docker",
    "Kubernetes",
    "Python",
    "Java",
    "JavaScript",
    "Node.js",
    "React",
    # General Project Keywords
    "scope",
    "objectives",
    "deliverables",
    "milestones",
    "timeline",
    "budget",
    "constraints",
    "assumptions",
    "dependencies",
    "risks",
    # Business & Functional Requirements
    "business requirements",
    "functional requirements",
    "user stories",
    "use cases",
    "business logic",
    "workflows",
    "process flow",
    "user interface",
    "user experience",
    "acceptance criteria",
    # Non-Functional Requirements
    "performance",
    "scalability",
    "reliability",
    "availability",
    "security",
    "compliance",
    "maintainability",
    "portability",
    "usability",
    "disaster recovery",
    # Technical Specification Keywords
    "technical specifications",
    "architecture",
    "data model",
    "data flow",
    "integration",
    "API",
    "protocols",
    "database",
    "system requirements",
    "hardware",
    "software",
    # Testing and Validation
    "testing",
    "validation",
    "quality assurance",
    "test cases",
    "unit testing",
    "integration testing",
    "system testing",
    "performance testing",
    "regression testing",
    "UAT (User Acceptance Testing)",
    # Project Management and Stakeholders
    "project management",
    "stakeholders",
    "roles and responsibilities",
    "communication plan",
    "resource allocation",
    "project timeline",
    "implementation plan",
    "change management",
    "training plan",
    # Version Control and Documentation
    "version control",
    "documentation",
    "change log",
    "version history",
    "release notes",
    "software documentation",
    "technical documentation",
    # Legal and Regulatory Terms
    "compliance",
    "regulatory requirements",
    "legal implications",
    "licenses",
    "privacy policy",
    "data protection",
    # Specific Technologies and Frameworks
    "cloud services",
    "frontend",
    "backend",
    "full stack",
    "database management",
    "web services",
    "microservices",
    "containers",
    "virtualization",
    "machine learning",
    "artificial intelligence",
    "blockchain",
    "IoT (Internet of Things)",
    # old
    "Software Development Life Cycle",
    "SDLC Phases",
    "Requirements Analysis",
    "System Design",
    "Database Design",
    "Frontend Development",
    "Backend Development",
    "Unit Testing",
    "Integration Testing",
    "PLanguage",
    "System Testing",
    "User Acceptance Testing",
    "Deployment Automation",
    "Release Management",
    "Version Control System",
    "Git Branching Strategies",
    "Continuous Integration Tools",
    "Continuous Deployment Pipelines",
    "DevOps Practices",
    "Infrastructure as Code",
    "Container Orchestration",
    "Microservices Architecture",
    "Monolithic Architecture",
    "Serverless Computing",
    "RESTful APIs",
    "SOAP Protocols",
    "Database Management Systems",
    "Relational Databases",
    "NoSQL Databases",
    "In-Memory Databases",
    "Cache Systems",
    "SQL Optimization",
    "ORM (Object-Relational Mapping)",
    "Middleware",
    "Message Queue Systems",
    "Load Balancing",
    "Security Best Practices",
    "Authentication",
    "Authorization",
    "Cryptographic Techniques",
    "Threat Modeling",
    "Penetration Testing",
    "Code Review Guidelines",
    "Static Code Analysis",
    "Code Quality Metrics",
    "Code Refactoring Techniques",
    "Technical Debt Management",
    "Programming Languages",
    "Java Programming",
    "Python Programming",
    "JavaScript Frameworks",
    "C++ Language Features",
    "C# Programming",
    "Ruby Language Constructs",
    "PHP Development",
    "Swift Language",
    "Objective-C Programming",
    "TypeScript Essentials",
    "Web Development Frameworks",
    "Backend Frameworks",
    "Frontend Frameworks",
    "UI/UX Design Principles",
    "Responsive Web Design",
    "Cross-Browser Compatibility",
    "Single Page Applications (SPA)",
    "Progressive Web Apps (PWA)",
    "Mobile App Development",
    "iOS Development",
    "Android Development",
    "Cross-Platform Development",
    "Augmented Reality (AR)",
    "Virtual Reality (VR)",
    "Project Management Methodologies",
    "Agile Scrum",
    "Kanban Boards",
    "Lean Development",
    "Waterfall Model",
    "Critical Path Analysis",
    "Gantt Chart Planning",
    "Risk Identification",
    "Change Control Process",
    "Quality Assurance Practices",
    "Test Automation",
    "Behavior-Driven Development (BDD)",
    "Performance Testing",
    "Usability Testing",
    "Regression Testing",
    "Test-Driven Development (TDD)",
    "Code Versioning Strategies",
    "Feature Branching",
    "Gitflow Workflow",
    "Trunk-Based Development",
    "Git Best Practices",
    "Continuous Integration Tools",
    "Jenkins Automation",
    "Travis CI Setup",
    "CircleCI Configurations",
    "Configuration Management",
    "Infrastructure as Code (IaC)",
    "Terraform Usage",
    "Ansible Playbooks",
    "Container Orchestration",
    "Docker Containerization",
    "Kubernetes Deployments",
    "Service Mesh",
    "Serverless Architecture",
    "AWS Lambda Functions",
    "Azure Functions",
    "Google Cloud Functions",
    "Microservices Design Principles",
    "Service-Oriented Architecture (SOA)",
    "API Gateway Implementation",
    "RESTful API Design",
    "GraphQL Schemas",
    "Database Sharding",
    "Event-Driven Architecture",
    "Message Queue Systems",
    "Apache Kafka Setup",
    "RabbitMQ Configuration",
    "Load Balancer Configuration",
    "Web Application Security",
    "Secure Coding Practices",
    "OAuth and OpenID Connect",
    "JWT Authentication",
    "SSL/TLS Encryption",
    "Firewall Configurations",
    "Vulnerability Management",
    "DevSecOps Practices",
    "Security Incident Response",
    "Authentication Protocols",
    "Role-Based Access Control (RBAC)",
    "Multi-Factor Authentication (MFA)",
    "Code Review Guidelines",
    "Static Code Analysis Tools",
    "Code Metrics Analysis",
    "Refactoring Patterns",
    "Code Smells Detection",
    "Automated Code Review",
    "Technical Debt Management",
    "Agile Estimation Techniques",
    "Planning Poker",
    "Story Points Estimation",
    "Wideband Delphi Method",
    "PERT Analysis",
    "Use Case Points (UCP)",
    "Function Points Analysis",
    "COCOMO Model",
    "Monte Carlo Simulation",
    "Velocity Tracking",
    "Burn Down Charts",
    "Critical Path Analysis",
    "Gantt Chart Visualization",
    "Project Risk Management",
    "Risk Identification",
    "Risk Assessment",
    "Risk Mitigation Strategies",
    "Change Management Processes",
    "Change Request Forms",
    "Change Impact Analysis",
    "Continuous Improvement",
    "Quality Management Systems",
    "ISO 9001 Standards",
    "Capability Maturity Model Integration (CMMI)",
    "Six Sigma Methodology",
    "Lean Six Sigma Principles",
    "Agile Metrics Tracking",
    "Cycle Time Metrics",
    "Lead Time Metrics",
    "Throughput Metrics",
    "Work in Progress (WIP) Limits",
    "Cumulative Flow Diagrams",
    "Value Stream Mapping",
    "Kaizen Principles",
    "Retrospective Meetings",
    "Scrum Master Role",
    "Product Owner Responsibilities",
    "Team Collaboration Tools",
    "Communication Channels",
    "Virtual Collaboration Tools",
    "JIRA Software",
    "Trello Boards",
    "Asana Project Management",
    "Microsoft Project",
    "VersionOne Agile Platform",
    "Redmine Issue Tracking",
    "Confluence Documentation",
    "Technical Documentation",
    "User Manuals",
    "API Documentation",
    "System Architecture Diagrams",
    "UML Diagrams",
    "Flowcharts",
    "Wireframing Tools",
    "Mockup and Prototyping Tools",
    "Requirements Traceability Matrix",
    "User Story Mapping",
    "Feature Driven Development (FDD)",
    "Behavior Driven Development (BDD)",
    "Test-Driven Development (TDD)",
    "Pair Programming",
    "Mob Programming",
    "Cross-Functional Teams",
    "Team Dynamics",
    "Conflict Resolution Strategies",
    "Motivational Theories",
    "Agile Leadership",
    "Servant Leadership",
    "Transformational Leadership",
    "Emotional Intelligence in Leadership",
    "Distributed Teams Management",
    "Remote Collaboration Tools",
    "Time Zone Management",
    "Cultural Awareness in Teams",
    "Diversity and Inclusion in Tech",
    "Code of Conduct in Teams",
    "Mentorship Programs",
    "Knowledge Transfer Practices",
    "Community of Practice",
    "Professional Development Plans",
    "Tech Conference Attendance",
    "Open Source Contributions",
    "Continuous Learning Culture",
    "Tech Trends Monitoring",
    "Innovation Frameworks",
    "Design Thinking Principles",
    "Lean Startup Methodology",
    "Agile Coaching",
    "Scrum Certification",
    "Kanban Training",
    "DevOps Certifications",
    "Cloud Service Provider Certifications",
    "Security Certifications",
    "Project Management Certifications",
    "Agile Transformation Strategies",
    "Scaled Agile Framework (SAFe)",
    "Large-Scale Scrum (LeSS)",
    "Disciplined Agile (DA)",
    "Feature-Driven Development (FDD)",
    "DevSecOps Adoption",
    "Cloud-Native Development",
    "Serverless Computing Trends",
    "Edge Computing",
    "IoT (Internet of Things) Development",
    "Quantum Computing",
    "Blockchain Technology",
    "Artificial Intelligence (AI) in Development",
    "Machine Learning Applications",
    "Natural Language Processing (NLP)",
    "Computer Vision",
    "Robotic Process Automation (RPA)",
    "Ethical AI Practices",
    "Explainable AI",
    "Responsible AI Development",
    "Bias Detection in AI",
    "GDPR Compliance in Tech",
    "Data Privacy Regulations",
    "Cybersecurity Best Practices",
    "Incident Response Plans",
    "Disaster Recovery Planning",
    "Business Continuity Management",
    "Compliance as Code",
    "Serverless Security",
    "Container Security",
    "AI Model Security",
    "Web Application Firewalls",
    "Zero Trust Network Architecture",
    "Cloud Security Controls",
    "Security Information and Event Management (SIEM)",
    "Secure Software Development Lifecycle (SSDLC)",
    "Zero-Day Vulnerability Response",
    "Cloud-Native Security",
    "API Security Best Practices",
    "Security Awareness Training",
    "Ephemeral Environments",
    "Chaos Engineering",
    "Game Days for Resilience Testing",
    "Cloud Cost Management",
    "Reserved Instances Optimization",
    "Spot Instances Utilization",
    "Auto Scaling Strategies",
    "Performance Monitoring Tools",
    "Log Management Solutions",
    "Application Performance Management (APM)",
    "Infrastructure Monitoring",
    "Security Incident Response Plan (SIRP)",
    "Forensic Analysis",
    "Threat Intelligence",
    "Secure Code Review",
    "Red Team Assessments",
    "Blue Team Defenses",
    "Purple Team Exercises",
    "DevOps Culture",
    "Continuous Learning",
    "Feedback Loops",
    "Blameless Post-Mortems",
    "Collaborative Decision-Making",
    "Infrastructure Resilience",
    "Immutable Infrastructure",
    "ChatOps Practices",
    "Site Reliability Engineering (SRE)",
    "Observability in Systems",
    "Distributed Tracing",
    "Serverless Observability",
    "Microservices Monitoring",
    "Data-Driven Decision Making",
    "Key Performance Indicators (KPIs)",
    "OKR (Objectives and Key Results)",
    "Balanced Scorecard",
    "Value Stream Analysis",
    "Lean Analytics",
    "Data Warehousing",
    "Business Intelligence (BI)",
    "Data Governance",
    "Data Quality Management",
    "Data Integration Strategies",
    "Data Migration Plans",
    "ETL (Extract, Transform, Load) Processes",
    "Data Lakes",
    "Big Data Technologies",
    "Hadoop Ecosystem",
    "Spark Data Processing",
    "NoSQL Database Models",
    "Graph Databases",
    "Document-Oriented Databases",
    "Column-Family Stores",
    "Time-Series Databases",
    "Blockchain Data Structures",
    "Decentralized Identity",
    "Smart Contracts Development",
    "Consensus Algorithms",
    "Decentralized Finance (DeFi)",
    "Web3.0 Concepts",
    "Quantum Computing Algorithms",
    "Quantum Cryptography",
    "Quantum Machine Learning",
    "Quantum Information Theory",
    "Quantum Programming Languages",
    "Quantum Cloud Computing",
    "Quantum Internet",
    "Quantum Sensors",
    "Quantum Supremacy",
    "Biocomputing",
    "DNA Computing",
    "Neuromorphic Computing",
    "Cyber-Physical Systems (CPS)",
    "Digital Twins",
    "Edge Computing Architectures",
    "Fog Computing",
    "Intelligent Edge Devices",
    "5G Networks",
    "Augmented Reality Development",
    "AR Content Creation Tools",
    "Virtual Reality Development",
    "VR Simulation Platforms",
    "Mixed Reality Applications",
    "Extended Reality (XR)",
    "Blockchain for AR/VR",
    "Smart Cities Technology",
    "IoT Sensors",
    "IoT Connectivity Standards",
    "IoT Edge Computing",
    "IoT Security Measures",
    "IoT Data Analytics",
    "IoT Device Management",
    "IoT Platform Integration",
    "Smart Grids",
    "Industrial IoT (IIoT)",
    "Blockchain in IoT",
    "Quantum IoT",
    "Quantum Communication Networks",
    "Quantum Key Distribution (QKD)",
    "Quantum Internet of Things (QIoT)",
    "Blockchain Consensus Mechanisms",
    "Proof of Work (PoW)",
    "Proof of Stake (PoS)",
    "Delegated Proof of Stake (DPoS)",
    "Practical Byzantine Fault Tolerance (PBFT)",
    "Directed Acyclic Graphs (DAG)",
    "Hashgraph Consensus",
    "Sharding in Blockchain",
    "Cross-Chain Interoperability",
    "Smart Contracts Platforms",
    "Decentralized Autonomous Organizations (DAO)",
    "Non-Fungible Tokens (NFT)",
    "Decentralized Finance (DeFi) Platforms",
    "Central Bank Digital Currencies (CBDC)",
    "Quantum-Safe Cryptography",
    "Post-Quantum Cryptography",
    "Quantum Key Distribution (QKD)",
    "Quantum-Secure Blockchain",
    "Quantum Machine Learning Algorithms",
    "Quantum Data Encryption",
    "Quantum-Safe Cloud Computing",
    "Quantum-Safe Internet",
    "Quantum-Safe VPNs",
    "Quantum-Safe Hardware Security Modules (HSM)",
    "Quantum-Safe Public Key Infrastructure (PKI)",
    "Quantum-Safe Digital Signatures",
    "Quantum-Safe Certificate Authorities (CA)",
]
